name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest
    strategy:
      matrix:
       run-config:
          - { scheme: 'CI_macOS', destination: 'platform=macOS' }
          - { scheme: 'CI_IOS', destination: 'platform=iOS Simulator, id:D211B988-BEF9-4A39-8A97-A9BBF823F27C, OS:15.2, name:iPhone 8' }

    steps:
    - uses: actions/checkout@v2
    - name: Build and test 
      run: xcodebuild clean build test -project "EssentialFeed.xcodeproj" -scheme  '${{ matrix.run-config['scheme'] }}'  -destination '${{ matrix.run-config['destination'] }}' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    

      

