name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest
    strategy:
      matrix:
       run-config:
          - { scheme: 'CI_macOS', destination: 'platform=macOS' }
           - { scheme: 'CI_IOS', destination: 'platform=macOS' }


    steps:
    - uses: actions/checkout@v2
    - name: Build and test 
      run: xcodebuild clean build test -project "EssentialFeed.xcodeproj" -scheme  '${{ matrix.run-config['scheme'] }}'  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
 

      

