name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: macos-latest
    strategy:
      matrix:
       run-config:
          - { scheme: 'CI_macOS', destination: 'platform=macOS' }
          - { scheme: 'CI_IOS', destination: "{platform=iOS Simulator, id=146AC047-AC86-4BBF-B6D3-8D08520EDDC9, OS=15.2, name=iPhone 11 Pro}" }

    steps:
    - uses: actions/checkout@v2
    - name: Build and test 
      run: xcodebuild clean build test -project "EssentialFeed.xcodeproj" -scheme  '${{ matrix.run-config['scheme'] }}'  -destination '${{ matrix.run-config['destination'] }}' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
    

      

